// <auto-generated />
using System;
using Cargo4You.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cargo4You.Migrations
{
    [DbContext(typeof(CargoDbContext))]
    partial class CargoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Cargo4You.Models.CargoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CalculationCm3String")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalculationKgString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DimensionPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ValidationCm3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationKg1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationKg2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CargoPartners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculationCm3String = "<=1000price10;>1000&&<=2000price20",
                            CalculationKgString = "<=2price15;>2&&<=15price18;>15&&<=20price35",
                            DimensionPrice = 0.0,
                            Name = "Cargo 4 You",
                            Price = 0.0,
                            ValidationCm3 = "<=2000",
                            ValidationKg1 = "<=20",
                            ValidationKg2 = "",
                            WeightPrice = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CalculationCm3String = "<=1000price11,99;>1000&&<=1700price21,99",
                            CalculationKgString = ">10&&<=15price16,5;>15&&<=25price36,5;>25price40+0,417",
                            DimensionPrice = 0.0,
                            Name = "Ship Faster",
                            Price = 0.0,
                            ValidationCm3 = "<=1700",
                            ValidationKg1 = ">10",
                            ValidationKg2 = "<=30",
                            WeightPrice = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CalculationCm3String = "<=1000price9,5;>1000&&<=2000price19,5;>2000&&<=5000price48,5;>5000price147,5",
                            CalculationKgString = ">=10&&<=20price16,99;>20&&<=30price33,99;>30price43,99+0,41",
                            DimensionPrice = 0.0,
                            Name = "Malta Ship",
                            Price = 0.0,
                            ValidationCm3 = ">=500",
                            ValidationKg1 = ">=10",
                            ValidationKg2 = "",
                            WeightPrice = 0.0
                        });
                });

            modelBuilder.Entity("Cargo4You.Models.UserActivityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
